# Стадия 1: збірка
FROM golang:1.24-alpine3.21 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main ./cmd/main.go

# Стадия 2: запуск
FROM alpine:3.21

WORKDIR /app
RUN apk add --no-cache \
    ca-certificates \
    tzdata \
    mysql-client \
    bash
COPY --from=builder /app/main .



EXPOSE 8000

CMD ["./main"]
